---
title: "Capstone Project Proposal"
author: "Karthic Venkatesh Navaladi"
date: "3/7/2018"
output: html_document
---

## Capstone Project Proposal
###### *Introduction to Data Science by Springboard*
### Women's eCommerce Clothing Reviews Analysis 
##### Submission By Karthic Venkatesh Navaladi 
##### Mentored By Raghunandan Patthar  


### Introduction
eCommerce - the activity of buying or selling online has been growing enormously over the past few years. The developed world has already started witnessing the retailers closing the physical stores and moving towards digital commerce. It's prime time to analyze the huge volume of various transactional data of an eCommerce company to take the next step forward. 


### The Problem
Consumers write reviews about different products they purchase online. These reviews play a vital role for new/existing consumers who are exploring to make purchases. Reviews are generally written by wide variety of consumers who can be different in age, sex, products they prefer, writing reviews without buying products etc. This offers a challenge for the company to come up with decisions in marketing, selling, buying, differentiating prime vs non-prime consumers etc. This project aims at helping the eCommerce retailer to come up with substantial decisions in determining the various factors as mentioned above. 


### The Client
The client here is an eCommerce retailer selling women's clothing 


### The Data
The data for this project is sourced from Kaggle. This dataset contains about 23487 rows and 11 columns. Dataset link: [*Womens_Clothing_reviews.csv*](https://www.kaggle.com/nicapotato/womens-ecommerce-clothing-reviews/data/Womens Clothing E-Commerce Reviews.csv) 


### The Approach
The below steps highlights the approaching steps for this Capstone project:

1. Data Wrangling and Cleaning
	+ Deal with missing values: Use domain information to determine if missing values should be discarded
	+ Dropping columns that are irrelevant to the analysis
	+ Rearrange and transform dataset for cleaner analysis.


### The Deliverables
The deliverables for this project will include a report of all the findings, a slide deck and R code, all of which will be published on GitHub.


### Specific questions to be explored
1.Products Vs Consumers - How are we going to treat the prime consumers differently? 
2.Products Vs Gender Vs Age - Which products are most preferred by Ladies Vs Gents at different age groups? 
3.Department Vs Sales - Which Department would have more sales compared to others? 
4.Consumers Vs Review - How we are going to treat the review consumers differently? 
5.Products Vs Review - Which products are likely to get more positive reviews?
6.How can we sell products in bundle using the reviews?
7.Determining the age of consumers from reviews. 




 
